# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rib8_PibBErkYppV0SSHmsrbpPt9Q_Vq
"""

import streamlit as st
import faiss
import pickle
import numpy as np
from PIL import Image
import torch
from torchvision import models, transforms

# ---- Load pretrained ResNet ----
@st.cache_resource
def load_model():
    model = models.resnet50(pretrained=True)
    model = torch.nn.Sequential(*list(model.children())[:-1])  # remove final FC
    model.eval()
    return model

model = load_model()

# ---- Image preprocessing ----
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

def extract_feature(img):
    x = transform(img).unsqueeze(0)
    with torch.no_grad():
        vec = model(x).squeeze().numpy()
    return vec / np.linalg.norm(vec)

# ---- Load FAISS index and image paths ----
@st.cache_resource
def load_index():
    index = faiss.read_index("yoga_index.faiss")
    with open("yoga_img_paths.pkl", "rb") as f:
        img_paths = pickle.load(f)
    return index, img_paths

index, img_paths = load_index()

# ---- Streamlit UI ----
st.title("🧘 Yoga Pose Semantic Search")
uploaded_file = st.file_uploader("Upload a yoga pose image", type=["jpg", "png"])

if uploaded_file:
    query_img = Image.open(uploaded_file).convert("RGB")
    st.image(query_img, caption="Uploaded Image", use_column_width=True)

    vec = extract_feature(query_img).astype("float32").reshape(1, -1)
    D, I = index.search(vec, k=5)

    st.subheader("🔍 Top 5 Most Similar Poses:")
    for idx in I[0]:
        st.image(img_paths[idx], width=200)